# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web Concepts
email: erik.wilde@dret.net
description: > # this means to ignore newlines until "baseurl:"
  Concepts that matter for the Web.
  Document your APIs by documenting their Web Concepts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://webconcepts.info" # the base hostname & protocol for your site
twitter_username: dret
github_username:  dret

# Build settings
markdown: kramdown
